### ISSUE TITLE
Stopped working after update to 0.14.0

### ISSUE THREAD

**Issue by churanov** [phillipsj/Cake.Squirrel#32]
Could not load ...Cake.Squirrel.dll (missing netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
Cake.exe : build.cake(156,21): error CS0246: The type or namespace name 'SquirrelSettings' could not be found (are you missing a using directive or an assembly reference?)

build.cake(163,3): error CS0103: The name 'Squirrel' does not exist in the current context
Error: 
Error(s) occurred when compiling build script:
build.cake(156,21): error CS0246: The type or namespace name 'SquirrelSettings' could not be found (are you missing a using directive or an assembly reference?)
build.cake(163,3): error CS0103: The name 'Squirrel' does not exist in the current context
`

**Comment by phillipsj** [comment]
What version of Cake are you using?

**Comment by phillipsj** [comment]
Also did you have your addin pinned?   Here is how you can pin versions to
get back up and running.  Thanks for the bug report.

**Comment by churanov** [comment]
Cake version="0.30.0"

#addin nuget:?package=Cake.Squirrel&version=0.13.0 - work ok

#addin nuget:?package=Cake.Squirrel&version=0.14.0 - gives error
_Could not load Cake.Squirrel.dll (missing netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)_

**Comment by phillipsj** [comment]
I have tested it using .NET 4.6.2 and .NET 4.7.x and it works without issue.  Please continue using 0.13.0 or upgrade your .net framework.
